name: child_goods_store_flutter
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# Deplay Step
# 1. Change version
#
# [Android] =======
# 1. Change `android/key.properties` - `flutter.versionName`, `flutter.versionCode`
# 2. cd android
# 3. fastlane beta
#
# [iOS] =======
# 1. cd ios
# 2. fastlane version - set version to pubspec.yaml's version
# 3. fastlane beta
version: 0.0.2+2

environment:
  sdk: ">=3.2.3 <4.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  bloc: ^8.1.3
  flutter_bloc: ^8.1.4
  bloc_concurrency: ^0.2.4
  path_provider: ^2.1.2
  equatable: ^2.0.5
  go_router: ^13.2.0
  dio: ^5.4.1
  flutter_secure_storage: ^9.0.0
  firebase_core: ^2.25.5
  firebase_auth: ^4.17.6
  firebase_analytics: ^10.8.9
  firebase_messaging: ^14.7.19
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  intl: ^0.18.1
  font_awesome_flutter: ^10.7.0
  google_sign_in: ^6.2.1
  kakao_flutter_sdk_user: ^1.8.0
  flutter_naver_login: ^1.8.0
  flutter_svg: ^2.0.10+1
  image_picker: ^1.0.7
  kpostal: ^0.5.1
  carousel_slider: ^4.2.1
  percent_indicator: ^4.2.3
  extended_nested_scroll_view: ^6.2.1
  web_socket_channel: ^2.4.5
  stomp_dart_client: ^2.0.0
  flutter_advanced_switch: ^3.1.0
  flutter_native_splash: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0
  flutter_flavorizr: ^2.2.1
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  build_runner: ^2.4.8

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/svgs/
    - assets/jsons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

# Flavor settings
flavorizr:
  flavors:
    dev:
      app:
        name: "DEV 키디마켓"
      android:
        applicationId: "dev.io.github.u3C1S.child_goods_store_flutter"
        icon: "assets/images/child_goods_store_icon_1024_bg.png"
        firebase:
          config: "android/firebase/dev/google-services.json"
      ios:
        bundleId: "dev.io.github.u3C1S.childGoodsStoreFlutter"
        icon: "assets/images/child_goods_store_icon_1024_bg.png"
        firebase:
          config: "ios/firebase/dev/GoogleService-Info.plist"

    prod:
      app:
        name: "키디마켓"
      android:
        applicationId: "io.github.u3C1S.child_goods_store_flutter"
        icon: "assets/images/child_goods_store_icon_1024_bg.png"
        firebase:
          config: "android/firebase/prod/google-services.json"
      ios:
        bundleId: "io.github.u3C1S.childGoodsStoreFlutter"
        icon: "assets/images/child_goods_store_icon_1024_bg.png"
        firebase:
          config: "ios/firebase/prod/GoogleService-Info.plist"

# Native splash settings
flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/child_goods_store_icon_1024.png
  android_12:
    color: "#FFFFFF"
    image: assets/images/child_goods_store_icon_1024.png
  android: true # Generate splash screen for Android
  ios: true # Generate splash screen for iOS
